name: Collect data 

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute py script
        run: |
          cd scripts/
          python -m pip install PyGithub
          GITHUB_PAT=${{ secrets.ACCESS_TOKEN }} python fetch.py 
          python package-retrieve.py 
      - name: Check Git status
        id: git
        shell: bash
        run: |
          RESULT=$(git status)
          echo "::set-output name=status::$RESULT"
      - name: Commit files
        if: "!contains(steps.git.outputs.result, 'working tree clean')"
        run: |
          git config --local user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Other task
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          token: ${{ secrets.ACCESS_TOKEN }}
