name: Collect data 

on:
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute py script
        run: |
          cd scripts/
          python fetch.py 
          python package-retrieve.py 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Git status
        id: git
        shell: bash
        run: |
          RESULT=$(git status)
          echo "::set-output name=status::$RESULT"
      - name: Other task
        if: ! contains(steps.git.outputs.result, 'working tree clean')
        uses:./.github/workflows/main.yml
