name: Gatsby Deploy

on:
  push:
    branches:
      - 'deploy'
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: '--prefix-paths'
