name: Deploy

on: [workflow_call, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm run build

      - name: Archive the build results
        shell: "tar -czf /tmp/build.tar.gz public/"
      - name: Upload the build archive
        uses: actions/upload-artifact@v1
        with:
          name: build.tar.gz
          path: /tmp/build.tar.gz
