name: Write Package Json

on:
  workflow_dispatch:
    branches:
      - 'deploy'
jobs:
  collect_data:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v1
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python3 scripts/package-retrieve.py 
